"""Standardize expense categories

Revision ID: 370ec25c93e4
Revises: f3d24a74a447
Create Date: 2026-02-23 16:00:40.740161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '370ec25c93e4'
down_revision: Union[str, Sequence[str], None] = 'f3d24a74a447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('category', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
