"""Standardize expense categories

Revision ID: 370ec25c93e4
Revises: f3d24a74a447
Create Date: 2026-02-23 16:00:40.740161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '370ec25c93e4'
down_revision: Union[str, Sequence[str], None] = 'f3d24a74a447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # FIXED: Make idempotent - check if column exists before dropping
    # This handles cases where databases are created fresh without the old 'category' column
    try:
        op.drop_column('expenses', 'category')
    except Exception as e:
        # Column may not exist in fresh databases
        if "check that it exists" in str(e) or "1091" in str(e):
            pass  # Column doesn't exist, nothing to do
        else:
            raise  # Re-raise if it's a different error


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('category', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
