version = 5.4.0
archive_dir = /etc/letsencrypt/archive/tytahj.inphora.net
cert = /etc/letsencrypt/live/tytahj.inphora.net/cert.pem
privkey = /etc/letsencrypt/live/tytahj.inphora.net/privkey.pem
chain = /etc/letsencrypt/live/tytahj.inphora.net/chain.pem
fullchain = /etc/letsencrypt/live/tytahj.inphora.net/fullchain.pem
[renewalparams]
account = 97380224dbd9d1ffdd8515d4ede3b3b6
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
