"""Add PWA fields to OrganizationConfig

Revision ID: 2f41250cf12a
Revises: 370ec25c93e4
Create Date: 2026-02-24 13:50:58.428679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f41250cf12a'
down_revision: Union[str, Sequence[str], None] = '370ec25c93e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_config', sa.Column('pwa_short_name', sa.String(length=30), nullable=True))
    op.add_column('organization_config', sa.Column('pwa_description', sa.String(length=500), nullable=True))
    op.add_column('organization_config', sa.Column('pwa_icon_url', sa.String(length=500), nullable=True))
    op.add_column('organization_config', sa.Column('pwa_icon_512_url', sa.String(length=500), nullable=True))
    op.add_column('organization_config', sa.Column('pwa_splash_bg_color', sa.String(length=7), nullable=True))
    op.add_column('organization_config', sa.Column('pwa_theme_color', sa.String(length=7), nullable=True))
    op.add_column('organization_config', sa.Column('pwa_display', sa.String(length=20), nullable=True))
    op.add_column('organization_config', sa.Column('pwa_start_url', sa.String(length=100), nullable=True))
    op.add_column('organization_config', sa.Column('pwa_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_config', 'pwa_enabled')
    op.drop_column('organization_config', 'pwa_start_url')
    op.drop_column('organization_config', 'pwa_display')
    op.drop_column('organization_config', 'pwa_theme_color')
    op.drop_column('organization_config', 'pwa_splash_bg_color')
    op.drop_column('organization_config', 'pwa_icon_512_url')
    op.drop_column('organization_config', 'pwa_icon_url')
    op.drop_column('organization_config', 'pwa_description')
    op.drop_column('organization_config', 'pwa_short_name')
    # ### end Alembic commands ###
