"""Initial migration

Revision ID: f3d24a74a447
Revises: 
Create Date: 2026-02-23 15:51:12.363685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d24a74a447'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repayments', sa.Column('mpesa_transaction_id', sa.String(length=100), nullable=True))
    op.add_column('repayments', sa.Column('payment_method', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'repayments', ['mpesa_transaction_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repayments', type_='unique')
    op.drop_column('repayments', 'payment_method')
    op.drop_column('repayments', 'mpesa_transaction_id')
    # ### end Alembic commands ###
